spin_manifest_version = 2

[application]
name = "space-portal"
version = "0.1.0"
authors = ["Astronaut Cadet"]
description = "A beginner friendly Akamai Functions Space Lab"

[variables]
example_api_url = { default = "https://example.invalid/api" }
example_api_key = { default = "fake-example-key" }

[[trigger.http]]
route = "/..."
component = "space-portal"

[component.space-portal]
source = "dist/space-portal.wasm"
exclude_files = ["src/**/*.ts", "macro/**/*.ts", "node_modules/**"]
allowed_outbound_hosts = ["http://api.open-notify.org:80"]
key_value_stores = ["default"]

[component.space-portal.build]
command = "npm run build"
watch = ["src/**/*.ts", "package.json"]